[workspace]
authors = ["noureddine.khaous <noureddine.khaous@etu.u-paris.fr>"]
channels = ["conda-forge"]
name = "accented-speech-recognition"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
[dependencies]
numpy = ">=1.26,<2"
pandas = ">=3.0.2,<4"
loguru = ">=0.7.3,<0.8"
tqdm = ">=4.67.3,<5"
pyarrow = "==24.0.0"
ffmpeg = ">=8.0.1,<9"
python = ">=3.12,<3.13"


[pypi-dependencies]
soundfile = ">=0.13.1, <0.14"
praat-parselmouth = ">=0.4.7, <0.5"
snakemake = ">=9.19.0, <10"
librosa = ">=0.11.0, <0.12"
torch = ">=2.11.0, <3"
torchaudio = ">=2.11.0, <3"
torchcodec = ">=0.11.1, <0.12"
transformers = ">=5.6.2, <6"
pytest = ">=9.0.0, <10"
tensorboard = ">=2.20.0, <3"
jiwer = ">=4, <5"
datasets = ">=4, <5"
pyctcdecode = ">=0.5, <0.6"
kenlm = ">=0.3, <0.4"
ipykernel = ">=7, <8"
