# Condition B :
# Contrastive fine-tuning  + ASR fine-tuning sur AESRC2020 train

# snakemake --configfile configs/conditions/config_B.yaml --cores 1 prepare_aesrc_corpus > logs/evaluation/log_aesrc_preparation.log 2>&1 & 
# =============================================================================

data_preparation:
  arctic:
    raw_data_dir:       "data/raw/arctic"
    processed_data_dir: "data/processed/arctic"
    parquet_path:       "data/processed/arctic/corpus.parquet"
  
  l2_arctic:
    raw_data_dir:       "data/raw/l2_arctic/speakers"
    processed_data_dir: "data/processed/l2_arctic"
    parquet_path:       "data/processed/l2_arctic/corpus.parquet"
  
  aesrc:
    raw_data_dir:       "data/raw/aesrc/data"
    processed_data_dir: "data/processed/aesrc"
    parquet_path:       "data/processed/aesrc/corpus.parquet"
    csv_path:           "data/processed/aesrc/corpus.csv"
    dev_ratio:          0.10
    seed:               42


supervised_contrastive_training:
  # Same as Condition A — We can use the same checkpoints
  data:
    arctic_parquet_path:    "data/processed/arctic/corpus.parquet"
    l2_arctic_parquet_path: "data/processed/l2_arctic/corpus.parquet"
    sample_rate:     16000
    max_audio_len_s: 10.0
    split: "train"
  sampler:
    number_of_workers: 2
    k_utterances: 15
    s_speakers:   20
    n_batches:    100
    seed:         42
  model:
    model_name:      "facebook/wav2vec2-large-xlsr-53"
    proj_hidden_dim: 512
    proj_out_dim:    256
    vocab_size:      32
    min_frozen_layer: 0
    max_frozen_layer: 18
    ctc_lambda:  0.1
    temperature: 0.1
  training:
    epochs:             50
    learning_rate:      2e-5
    warmup_steps:       500
    use_ctc:            true
    tokenizer:          "facebook/wav2vec2-large-960h"
    device:             "cuda"
    checkpoint_dir:     "checkpoints/conditions/A/stage_2"   # même Stage 2 que A
    tensorboard_dir:    "tensorboard/conditions/A/stage_2"
    save_every_n_epochs: 5
    use_mixed_precision: false
  evaluation:
    output_dir:          "evaluation/conditions/A/stage_2"
    eval_every_n_epochs: 5
    eval_n_neg_samples:  1000
    eval_batch_size:     64
    retrieval_ks:        [1, 5, 10]
    eval_metrics:
      - alignment
      - uniformity
      - retrieval_at_5


asr_finetuning:
  data:
    dataset:                "aesrc" # choices : ["librispeech", "aesrc"]
    train_parquet:          "data/processed/aesrc/corpus.parquet"
    eval_parquet:           "data/processed/aesrc/corpus.parquet"
    max_duration_s:         20.0
    num_workers:            4

  model:
    model_name:             "facebook/wav2vec2-large-xlsr-53"
    stage2_checkpoint:      "checkpoints/conditions/A/stage_2/checkpoint_epoch050.pt"
  
  training:
    output_dir:             "checkpoints/conditions/B/stage_3"
    tensorboard_dir:        "tensorboard/conditions/B/stage_3"
    logging_dir:            "logs/conditions/B/stage_3"
    epochs:                 20
    batch_size:             16    # aesrc train
    backbone_lr:            1e-5
    head_lr:                1e-4
    weight_decay:           1e-2
    warmup_ratio:           0.1
    grad_clip:              1.0
    log_every:              50
    save_every:             5
    device:                 "cuda"

  evaluation:
    eval_every:             1
    eval_max_batches:       null